version: '3'

services:
    db:
      image : mysql:5.7
      command : --innodb-use-native-aio=0
      container_name : mysql_db
      environment:
        - MYSQL_DATABASE=m1
        - MYSQL_ROOT_PASSWORD=root
      volumes:
       - ./api/db/data:/var/lib/mysql
       - ./api/init/01.sql:/docker-entrypoint-initdb.d
      restart: always
      

    api:
      build: './api'
      container_name : 'node-container'
      restart: always
      volumes :
        - ./api:/home/node/api
      ports : 
        - "5001:5001"
      depends_on :
        - db

    web :
      image : php:7.2-apache
      container_name : php-container
      restart : always
      volumes:
        - ./website:/var/www/html
      ports : 
      - 80:80
      depends_on:
        - api
        - db